// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEZY5OMQukf0pgQnQhM3rEuS-2S9QUHM4',
    appId: '1:137182619854:android:2203c3405ea71d3cc3889f',
    messagingSenderId: '137182619854',
    projectId: 'quick-job-c8ebb',
    storageBucket: 'quick-job-c8ebb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcS-dgc5BDejfIyUWfXQ3DTyqaDmXEmfY',
    appId: '1:137182619854:ios:872f975ba4020ebbc3889f',
    messagingSenderId: '137182619854',
    projectId: 'quick-job-c8ebb',
    storageBucket: 'quick-job-c8ebb.firebasestorage.app',
    androidClientId:
        '137182619854-9unbaprvu5sjj7rd6s83c8hlbtoh1c7u.apps.googleusercontent.com',
    iosClientId:
        '137182619854-t8mgusf3t94f47agc1aci3iq579mj8kb.apps.googleusercontent.com',
    iosBundleId: 'com.quick.job.quickjob.quickJob',
  );
}
